# Digit Recognition Notebook

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [4]:
train_dataset = pd.read_csv('datasets/train.csv')

In [5]:
train_dataset.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
num_pixels = train_dataset.shape[1] - 1
num_labels = len(train_dataset.label.unique())
ys = tf.one_hot(train_dataset.label, depth=num_labels)
xs = train_dataset.iloc[:, 1:]
xs.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### *Creating a model*

In [11]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        keras.Input(shape=(num_pixels,)),
        layers.Dense(50, activation="sigmoid", name="hidden_layer1"),
        layers.Dense(20, activation="sigmoid", name="hidden_layer2"),
        layers.Dense(10, activation="sigmoid", name="output_layer"),
    ]
)

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 hidden_layer1 (Dense)       (None, 50)                39250

 hidden_layer2 (Dense)       (None, 20)                1020

 output_layer (Dense)        (None, 10)                210

=================================================================
Total params: 40,480
Trainable params: 40,480
Non-trainable params: 0
_________________________________________________________________

In [13]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

In [10]:
class StopOnPoint(tf.keras.callbacks.Callback):
    def __init__(self, point):
        super(StopOnPoint, self).__init__()
        self.point = point

    def on_epoch_end(self, epoch, logs=None): 
        accuracy = logs["accuracy"]
        self.epoch_end=epoch+1
        if accuracy >= self.point:
            self.model.stop_training = True

In [15]:
stop = StopOnPoint(0.95)
model.fit(
    x=xs,
    y=ys,
    epochs=10,
    validation_split=0.3,
    callbacks=[stop]
)
print(f'Training finished after {stop.epoch_end} epochs')

Epoch 1/25
919/919 [==============================] - 6s 7ms/step - loss: 0.0127 - accuracy: 0.9183 - val_loss: 0.0134 - val_accuracy: 0.9146
Epoch 2/25
919/919 [==============================] - 6s 6ms/step - loss: 0.0119 - accuracy: 0.9239 - val_loss: 0.0125 - val_accuracy: 0.9209
Epoch 3/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0130 - accuracy: 0.9161 - val_loss: 0.0130 - val_accuracy: 0.9167
Epoch 4/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0125 - accuracy: 0.9208 - val_loss: 0.0135 - val_accuracy: 0.9148
Epoch 5/25
919/919 [==============================] - 10s 11ms/step - loss: 0.0129 - accuracy: 0.9181 - val_loss: 0.0126 - val_accuracy: 0.9201
Epoch 6/25
919/919 [==============================] - 6s 6ms/step - loss: 0.0123 - accuracy: 0.9210 - val_loss: 0.0129 - val_accuracy: 0.9189
Epoch 7/25
919/919 [==============================] - 6s 7ms/step - loss: 0.0121 - accuracy: 0.9222 - val_loss: 0.0125 - val_accuracy: 0.9213
Epoch 8/25
919/919 [==============================] - 10s 11ms/step - loss: 0.0124 - accuracy: 0.9195 - val_loss: 0.0130 - val_accuracy: 0.9152
Epoch 9/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0118 - accuracy: 0.9250 - val_loss: 0.0122 - val_accuracy: 0.9214
Epoch 10/25
919/919 [==============================] - 4s 5ms/step - loss: 0.0117 - accuracy: 0.9254 - val_loss: 0.0127 - val_accuracy: 0.9195
Epoch 11/25
919/919 [==============================] - 6s 6ms/step - loss: 0.0115 - accuracy: 0.9250 - val_loss: 0.0119 - val_accuracy: 0.9255
Epoch 12/25
919/919 [==============================] - 7s 7ms/step - loss: 0.0113 - accuracy: 0.9279 - val_loss: 0.0118 - val_accuracy: 0.9253
Epoch 13/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0115 - accuracy: 0.9267 - val_loss: 0.0121 - val_accuracy: 0.9225
Epoch 14/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0115 - accuracy: 0.9270 - val_loss: 0.0122 - val_accuracy: 0.9222
Epoch 15/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0110 - accuracy: 0.9302 - val_loss: 0.0111 - val_accuracy: 0.9306
Epoch 16/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0109 - accuracy: 0.9301 - val_loss: 0.0120 - val_accuracy: 0.9227
Epoch 17/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0117 - accuracy: 0.9263 - val_loss: 0.0122 - val_accuracy: 0.9229
Epoch 18/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0112 - accuracy: 0.9301 - val_loss: 0.0116 - val_accuracy: 0.9256
Epoch 19/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0113 - accuracy: 0.9294 - val_loss: 0.0126 - val_accuracy: 0.9187
Epoch 20/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0113 - accuracy: 0.9284 - val_loss: 0.0120 - val_accuracy: 0.9232
Epoch 21/25
919/919 [==============================] - 5s 6ms/step - loss: 0.0117 - accuracy: 0.9265 - val_loss: 0.0132 - val_accuracy: 0.9157
Epoch 22/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0115 - accuracy: 0.9279 - val_loss: 0.0121 - val_accuracy: 0.9219
Epoch 23/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0114 - accuracy: 0.9267 - val_loss: 0.0118 - val_accuracy: 0.9245
Epoch 24/25
919/919 [==============================] - 5s 5ms/step - loss: 0.0109 - accuracy: 0.9311 - val_loss: 0.0110 - val_accuracy: 0.9287
Epoch 25/25
919/919 [==============================] - 6s 7ms/step - loss: 0.0108 - accuracy: 0.9316 - val_loss: 0.0120 - val_accuracy: 0.9229
Training finished after 25 epochs

In [16]:
test_dataset = pd.read_csv('datasets/test.csv')
test_dataset.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
outfile = 'submission.csv'

res = model.predict(test_dataset)
results = []
for i, res in enumerate(res):
    r = {'ImageId': i + 1, 'Label': np.argmax(res)}
    results.append(r)
    
submission = pd.DataFrame(results, columns=['ImageId', 'Label'])
submission.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      7
4        5      3

In [37]:
submission.to_csv(outfile, index=False)